### ISSUE TITLE
This fits that configuration

### ISSUE THREAD

**Issue by Herrengit** [ZxcVcx/G531GU-Hackintosh-OpenCore#1]
i7 9750 gtx1660 144hz Can I use it？

**Comment by ZxcVcx** [comment]
You can certainly use it, but I would recommend making your own, as I have a very **imperfect** and **old** version of this right now, and I am No time to update. It's not hard to do this, but it will take some time.

You can check this out [**dortania**](https://dortania.github.io/getting-started/)   ,  which has a tutorial on how to configure it, and a few other things you'll need.
